Tasks/task30
IStepanovSiberian/IStepanovSiberian pull request #11
Opened 2021-12-30 05:49 UTC by IStepanovSiberian

RetainFragment

2021-12-30 08:06 UTC, Aristman requested changes

2021-12-30 08:06 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
>  }
По заданию сохранение данных должно быть во фрагменте. Этот объект удалить

2021-12-30 08:06 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
> +        if (WeatherStore.weather == null) {
Сохранение и восстановление данных нужно делать из фрагмента.

2021-12-30 08:06 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
> +    private lateinit var weatherFragment: WeatherFragment
Так как по заданию мы сохраняем данные в retainFragment то нужно использовать фрагмент без вью. Только для сохранения данных

2021-12-30 08:06 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
> +            runningTasks.add(weatherFragment
Повторюсь - для чего используестя реактивщина?

2021-12-30 08:06 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
> +            }
Нужно проверять, есть ли соданный объект. и создавать его, атачить к менеджеру. Потом использовать его для сохранения\восстановления данных. Фрагмент дожен быть не тот, в котором показывается погода.
Подумай, можно ли для этого применить делегат lazy

2021-12-30 13:10 UTC, IStepanovSiberian commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava2:rxjava:2.1.13'
Для CompositeDisposable()

2022-01-04 12:42 UTC, Aristman approved these changes

2022-01-06 03:12 UTC, merged