Task 31 - MVVM Weather App
IStepanovSiberian/IStepanovSiberian pull request #12
Opened 2022-01-04 06:05 UTC by IStepanovSiberian

Скорее всего, нужно было добавить observer, но я не уверен куда конкретно его стоит добавить (если вообще стоит) - во Fragment, либо в MainActivity.

2022-01-04 12:53 UTC, Aristman requested changes

2022-01-04 12:53 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +    private val weatherData = MutableLiveData<List<ListParam>>()
В задании было указано не использовать LiveData. Оставляй так или если хочешь - переделай под обычные типы данных.

2022-01-04 12:53 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +                dataAdapter.submitList(weatherData.value)
Работать с адапетом из вьюмодели нельзя. Это - слой фрагмента или активити. Перенеси туда. Из вьюмодели получаем чистые данные.

2022-01-04 12:53 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +    fun restoreSavedWeather() {
У вьюмодели сделай метод для загрузки данных из сети и метод для получения уже загруженных данных. Это - не восстановление.

2022-01-04 12:53 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +        dataAdapter.submitList(weatherData.value)
Откуда это во вьюмодели? Поясни

2022-01-05 05:22 UTC, IStepanovSiberian commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +    private val weatherData = MutableLiveData<List<ListParam>>()
Переделаю под mutableListOf

2022-01-05 16:40 UTC, Aristman approved these changes

2022-01-06 03:13 UTC, merged