Task 33 - получение данных из ViewModel через LiveData
IStepanovSiberian/IStepanovSiberian pull request #15
Opened 2022-01-10 04:14 UTC by IStepanovSiberian

2022-01-10 07:02 UTC, Aristman requested changes

2022-01-11 02:10 UTC, IStepanovSiberian commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +        }
Посмотрел такой способ в официальной документации - https://developer.android.com/topic/libraries/architecture/viewmodel

2022-01-11 02:21 UTC, IStepanovSiberian commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +    fun getWeather(): LiveData<ArrayList<ListParam>> {
Посмотрел такой способ в официальной документации - https://developer.android.com/topic/libraries/architecture/viewmodel

2022-01-11 02:21 UTC, IStepanovSiberian commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +    private val weatherData: MutableLiveData<ArrayList<ListParam>> by lazy {
Посмотрел такой способ в официальной документации - https://developer.android.com/topic/libraries/architecture/viewmodel

2022-01-11 09:55 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/MainActivity.kt
> +            it?.let { dataAdapter.submitList(it) }
Чтобы не было таких "непонятных" ситуащий (две внутренние переменные  it) именуй внутренние переменный.
для примера 
{ result ->
...
}

2022-01-11 09:55 UTC, Aristman commented on app/src/main/java/com/example/siberianprostaging/WeatherViewModel.kt
> +            _weatherData.value = arrayListOf()
emptyList()

2022-01-11 10:56 UTC, Aristman approved these changes

2022-01-11 11:37 UTC, merged