Task 24
IStepanovSiberian/IStepanovSiberian pull request #3
Opened 2021-12-21 14:13 UTC by IStepanovSiberian

Исправил замечания по code review

2021-12-21 14:23 UTC, sergfirago requested changes

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        val weatherRService = Common.retrofitService
перенести в метод вместе с запросом

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        initRecyclerView(rv)
rv определить в методе

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/Response.kt
> +// Data classes for Responce
убрать везде

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/Response.kt
> +    val sea_level: Int? = null,
сделать используя аннотации seaLevel везде

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        val weatherRService = Common.retrofitService
переименовать retrofitService

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        val weatherRService = Common.retrofitService
переименовать Common

2021-12-21 14:23 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/RetrofitInterface.kt
> +interface RetrofitServices {
изменить имя

2021-12-21 14:28 UTC, IStepanovSiberian commented on app/src/main/java/com/example/retrofitforecaster/RetrofitInterface.kt
> +interface RetrofitServices {
Изменил на WeatherRetrofitService

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        rv.layoutManager = layoutManager
А для чего переменная layuotManager?

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +                Log.e("запрос", t.cause.toString())
Хардкод. В константы

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +                rv.adapter = adapter
Адаптер нужно инициализировать при создании RecyclerView. А тут нужно наполнять данными уже существующий адаптер. А так получается, что при каждом запросе адаптер пересоздается.

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/RecyclerAdapter.kt
> +class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
Очень непонятное имя. К чему относиться этот вьюхолдер?

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/RecyclerAdapter.kt
> +    private val cs = ConstraintSet()
Нейминг ни о чем. Переименуй

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/RecyclerAdapter.kt
> +                cs.applyTo(cl)
with(cs) {} или cs.run {}

2021-12-21 14:35 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/Response.kt
> +    val city: CityParams? = null
А для чего все поля по умолчанию null?

2021-12-21 14:37 UTC, IStepanovSiberian commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        rv.layoutManager = layoutManager
Сократил до recyclerView.layoutManager = LinearLayoutManager(this)

2021-12-21 14:46 UTC, IStepanovSiberian commented on app/src/main/java/com/example/retrofitforecaster/Response.kt
> +    val city: CityParams? = null
Согласен, было зря. Не сразу понял про аннотации

2021-12-21 14:54 UTC, IStepanovSiberian commented on app/src/main/java/com/example/retrofitforecaster/RecyclerAdapter.kt
> +class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
Переименовал

2021-12-21 16:46 UTC, IStepanovSiberian commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +                adapter.notifyDataSetChanged()
Согласен, лишний

2021-12-22 06:26 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +    val log_tag = "Запрос"
Правило нейминга - кэмелкейс. Для данного случая правильно было бы название logTag
И это хардкод. Строки нужно переносить в ресурсы. Либо перенести вне класса и сделать private const val

2021-12-22 06:26 UTC, Aristman commented on app/src/main/java/com/example/retrofitforecaster/Response.kt
> +    val `3h`: Double
?
Это что за нейминг?

2021-12-22 06:42 UTC, sergfirago requested changes

2021-12-22 06:42 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +const val LOG_TAG = "Запрос"
private

2021-12-22 06:42 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +    lateinit var dataAdapter: Adapter
private

2021-12-22 06:42 UTC, sergfirago commented on app/src/main/java/com/example/retrofitforecaster/MainActivity.kt
> +        dataAdapter = Adapter().also { recyclerView.adapter = it }
```kotlin
dataAdapter = Adapter()
recyclerView.adapter = dataAdapter
```
более читаемо по-моему

2021-12-22 07:42 UTC, closed without merging